import java.awt.Component;
import java.awt.event.MouseEvent;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.text.NumberFormat;
import java.util.Locale;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author desty
 */
public class pesanan extends javax.swing.JFrame {
    form_user formUser;

    /**
     * Creates new form cba
     */
    public pesanan() {
        initComponents();
        setTitle("Desty Mutiara Putri - 231011701062");
        groupButton();
        
        shoppingPane.addChangeListener(new javax.swing.event.ChangeListener() {
        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            summaryPaneStateChanged(evt);
        }
        });
    }
    
    public boolean userSudahIsi = false;
    
    
    private void summaryPaneStateChanged(javax.swing.event.ChangeEvent evt) {
    switch (shoppingPane.getSelectedIndex()) {
    case 0:
        break;

    case 1:
    if (TAA.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "No orders have been placed yet.", "Warning", JOptionPane.WARNING_MESSAGE);
        shoppingPane.setSelectedIndex(0);
    } else if (!userSudahIsi) {
        JOptionPane.showMessageDialog(this, "Please fill Name & Phone first by clicking Send.", "Error", JOptionPane.ERROR_MESSAGE);
        shoppingPane.setSelectedIndex(0);
    } else {
        TAA.setText(S1); // atau bisa juga pakai TA.getText()
        TAA.setEditable(false);
    }
    break;


    case 2:
    if (!userSudahIsi) {
        JOptionPane.showMessageDialog(this, "Please fill Name & Phone first by clicking Send.", "Warning", JOptionPane.WARNING_MESSAGE);
        shoppingPane.setSelectedIndex(0);
    } else if (formUser == null || formUser.getAlamat().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Address is still empty!", "Error", JOptionPane.ERROR_MESSAGE);
        shoppingPane.setSelectedIndex(0);
    } else {
        addressTextArea.setText(
            "Pizza Store\n" +
            "Jl. Viktor No.123\n" +
            "Tangerang Selatan, Indonesia\n\n" +
            formUser.getAlamat()
        );
    }
    break;




}

}





    private void groupButton(){
        ButtonGroup bg = new ButtonGroup();
        bg1.add(jRadioButton21);
        bg1.add(jRadioButton22);
        bg1.add(jRadioButton23);
        bg2.add(jRadioButton4);
        bg2.add(jRadioButton5);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        TA1 = new javax.swing.JTextArea();
        jFC = new javax.swing.JFileChooser();
        bg1 = new javax.swing.ButtonGroup();
        bg2 = new javax.swing.ButtonGroup();
        bg3 = new javax.swing.ButtonGroup();
        shoppingPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        monthSpinner = new javax.swing.JSpinner();
        daySpinner = new javax.swing.JSpinner();
        panelNya = new javax.swing.JPanel();
        temperaturScrollBar = new javax.swing.JScrollBar();
        FLabel = new javax.swing.JLabel();
        FTextFiled = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        gambar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TAA = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        totalCostTextField = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();

        TA1.setColumns(20);
        TA1.setRows(5);
        jScrollPane3.setViewportView(TA1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Toppings"));

        jCheckBox1.setText("Olives");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Green Peppers");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Tomatoes");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Onions");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setText("Mushrooms");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setText("Extra Cheese");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox1))
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Size"));

        jRadioButton21.setText("Small");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton22.setText("Medium");
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton23.setText("Large");
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jRadioButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(42, Short.MAX_VALUE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Crust"));

        jRadioButton4.setText("Thin Crust");

        jRadioButton5.setText("Thick Crust");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButton5)
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel3.setText("Sauce");

        jLabel1.setText("Pizza");

        jLabel4.setText("Quantity");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Tomato Sauce", "Barbecue Sauce", "Creamy Garlic", "Spicy Chili" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        monthSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"Spaghetti Bolognese", "Spaghetti Carbonara", "Spaghetti Aglio e Olio", "Spaghetti Marinara", "Spaghetti Pesto"}));
        monthSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        monthSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                monthSpinnerStateChanged(evt);
            }
        });

        daySpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        daySpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                daySpinnerStateChanged(evt);
            }
        });

        panelNya.setBackground(java.awt.Color.white);
        panelNya.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelNya.setPreferredSize(new java.awt.Dimension(280, 40));

        temperaturScrollBar.setMaximum(20);
        temperaturScrollBar.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        temperaturScrollBar.setPreferredSize(new java.awt.Dimension(200, 30));
        temperaturScrollBar.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                temperaturScrollBarAdjustmentValueChanged(evt);
            }
        });

        FLabel.setText("Spicy Level");

        FTextFiled.setText("0");

        javax.swing.GroupLayout panelNyaLayout = new javax.swing.GroupLayout(panelNya);
        panelNya.setLayout(panelNyaLayout);
        panelNyaLayout.setHorizontalGroup(
            panelNyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNyaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelNyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(temperaturScrollBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelNyaLayout.createSequentialGroup()
                        .addComponent(FLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        panelNyaLayout.setVerticalGroup(
            panelNyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNyaLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(panelNyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FLabel)
                    .addComponent(FTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(temperaturScrollBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cash", "Credit Card", "Debit", "QR Payment", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel2.setText("Payment Method");

        jButton1.setText("Buy Spaghetti ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("New Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageicon/newpackage/Spaghetti1.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Order Spaghetti ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(daySpinner)
                            .addComponent(monthSpinner))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelNya, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(293, 293, 293))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(daySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(monthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gambar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(panelNya, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap(545, Short.MAX_VALUE))
        );

        shoppingPane.addTab("Order", jPanel1);

        TAA.setColumns(20);
        TAA.setRows(5);
        jScrollPane5.setViewportView(TAA);

        jLabel7.setText("Total Price");

        jButton4.setText("Oder Details ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel7))
                            .addComponent(totalCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jButton4)))
                .addContainerGap(334, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(784, Short.MAX_VALUE))
        );

        shoppingPane.addTab("Order Summary", jPanel4);

        addressTextArea.setColumns(20);
        addressTextArea.setRows(5);
        jScrollPane7.setViewportView(addressTextArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(480, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(865, Short.MAX_VALUE))
        );

        shoppingPane.addTab("Delivery", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(shoppingPane, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(shoppingPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // Reset semua RadioButton
        JOptionPane.showMessageDialog(this, "Create a new order", "Informasi", JOptionPane.INFORMATION_MESSAGE);

        // Reset semua RadioButton di ButtonGroup
        bg1.clearSelection();
        bg2.clearSelection();
        bg3.clearSelection();

        // Reset semua CheckBox
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);

        // Reset ComboBox
        jComboBox1.setSelectedIndex(0);

        // Reset JList
        jList1.clearSelection();

        // Reset ScrollBar
        temperaturScrollBar.setValue(0); 
        // Reset Spinner
        monthSpinner.setValue("Spaghetti Marinara"); 
        daySpinner.setValue(1);          

        // Kosongkan TextArea
        //        TA.setText("");
//        jTextArea1.setText("");
        TAA.setText("");
        addressTextArea.setText("");
        //        TA2.setText("");
        totalCostTextField.setText("");

        // Tampilkan pesan
    }//GEN-LAST:event_jButton3ActionPerformed
    public void resetForm() {
        bg1.clearSelection();
        bg2.clearSelection();
        bg3.clearSelection();

        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);

        jComboBox1.setSelectedIndex(0);
        jList1.clearSelection();
        temperaturScrollBar.setValue(0);
        monthSpinner.setValue("Spaghetti Bolognese");
        daySpinner.setValue(1);

//        jTextArea1.setText("");
        TAA.setText("");
        addressTextArea.setText("");
        totalCostTextField.setText("");
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:\
        int pilihan = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Do you want to go out?",
            "Konfirmasi",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (pilihan == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
//private form_user formUser;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // harus pilih semua
        if (!(jRadioButton21.isSelected() || jRadioButton22.isSelected() || jRadioButton23.isSelected())) {
            JOptionPane.showMessageDialog(this, "PChoose one of the pizza menus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!(jCheckBox1.isSelected() || jCheckBox2.isSelected() || jCheckBox3.isSelected() ||
            jCheckBox4.isSelected() || jCheckBox5.isSelected() || jCheckBox6.isSelected())) {
        JOptionPane.showMessageDialog(this, "Select at least one topping!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
        }

        // Validasi jumlah pizza > 0
        int jumlahPizza = (int) daySpinner.getValue();
        if (jumlahPizza <= 0) {
            JOptionPane.showMessageDialog(this, "Enter the correct number of pizzas!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!(jRadioButton4.isSelected() || jRadioButton5.isSelected())) {
            JOptionPane.showMessageDialog(this, "Select Crust!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (jComboBox1.getSelectedIndex() == -1 || jComboBox1.getSelectedItem().toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select the type of sauce!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (jList1.getSelectedValuesList().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select the payment method!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // reset pesanan
        S1 = "";
        int hargaSize = 0;
        if (jRadioButton21.isSelected()) {
            S1 += "Size: " + jRadioButton21.getText() + "\n";
            hargaSize = 50000;
        }
        if (jRadioButton22.isSelected()) {
            S1 += "Size: " + jRadioButton22.getText() + "\n";
            hargaSize = 75000;
        }
        if (jRadioButton23.isSelected()) {
            S1 += "Size: " + jRadioButton23.getText() + "\n";
            hargaSize = 100000;
        }

        // Hitung topping
        int jumlahTopping = 10000;
        S1 += "Toppings:\n";
        if(jCheckBox1.isSelected()) { S1 += "- " + jCheckBox1.getText() + "\n"; jumlahTopping++; }
        if(jCheckBox2.isSelected()) { S1 += "- " + jCheckBox2.getText() + "\n"; jumlahTopping++; }
        if(jCheckBox3.isSelected()) { S1 += "- " + jCheckBox3.getText() + "\n"; jumlahTopping++; }
        if(jCheckBox4.isSelected()) { S1 += "- " + jCheckBox4.getText() + "\n"; jumlahTopping++; }
        if(jCheckBox5.isSelected()) { S1 += "- " + jCheckBox5.getText() + "\n"; jumlahTopping++; }
        if(jCheckBox6.isSelected()) { S1 += "- " + jCheckBox6.getText() + "\n"; jumlahTopping++; }

        // saus
        if (jComboBox1.getSelectedIndex() != -1) {
            S1 += "Jenis Saus: " + jComboBox1.getSelectedItem().toString() + "\n";
        }

        // metode pembayaran
        for (Object item : jList1.getSelectedValuesList()) {
            S1 += "Pembayaran: " + item.toString() + "\n";
        }

        // level pedas
        S1 += "Level Pedas: " + temperaturScrollBar.getValue() + "\n";

        // pizza jenis dan jumlah
        S1 += "Jenis Pizza: " + monthSpinner.getValue() + "\n";
        S1 += "Jumlah: " + jumlahPizza + "\n";

        // total cost
        int hargaTopping = jumlahTopping * 5;
        int totalPerPizza = hargaSize + hargaTopping;
        int totalCost = totalPerPizza * jumlahPizza;
        
        formUser = new form_user(this); // simpan sebagai variabel global
        formUser.setVisible(true);

        
        
        
        //        S1 += "Total Harga = Rp. " + totalCost + "\n"; // tampilkan total di TA

//        JOptionPane.showMessageDialog(this, "Order was successfully placed!");
        //        TA.setText(S1);
        TAA.setText(S1);
        NumberFormat formatter = NumberFormat.getNumberInstance(new Locale("id", "ID"));
        String formattedCost = "Rp. " + formatter.format(totalCost);
        //        S1 += "Total Harga = Rp. " + formattedCost + "\n";
        totalCostTextField.setText(formattedCost);
        totalCostTextField.setEditable(false);
//        addressTextArea.setText(jTextArea1.getText());
        addressTextArea.setEditable(false);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void temperaturScrollBarAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_temperaturScrollBarAdjustmentValueChanged
        // TODO add your handling code here:
        int level = temperaturScrollBar.getValue();
        tempF = level;
        Konversi();
    }//GEN-LAST:event_temperaturScrollBarAdjustmentValueChanged

    private void daySpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_daySpinnerStateChanged
        // TODO add your handling code here:
        //        TA.setText("Pizza : "+monthSpinner.getValue() + " , Jumlah :"+ " " + daySpinner.getValue());
    }//GEN-LAST:event_daySpinnerStateChanged

    private void monthSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_monthSpinnerStateChanged
        // TODO add your handling code here:
        String warna = (String) monthSpinner.getValue();
        String fileName;

        switch (warna) {
            case "Spaghetti Bolognese":
            fileName = "Spaghetti1.jpg";
            break;
            case "Spaghetti Carbonara":
            fileName = "Spaghetti2.jpg";
            break;
            case "Spaghetti Aglio e Olio":
            fileName = "Spaghetti3.jpg";
            break;
            case "Spaghetti Marinara":
            fileName = "Spaghetti4.jpg";
            break;
            case "Spaghetti Pesto":
            fileName = "Spaghetti5.jpg";
            break;
            default:
            fileName = "Spaghetti Marinara.jpg"; // ← Konsisten: dulunya "marghetita.jpeg", typo & beda ekstensi
            break;
        }

        java.net.URL imgUrl = getClass().getResource("/imageicon/newpackage/" + fileName);

        if (imgUrl != null) {
            gambar.setIcon(new javax.swing.ImageIcon(imgUrl));
        } else {
            System.err.println("Gambar tidak ditemukan: " + fileName);
        }
        //        TA.setText("Pizza : " + monthSpinner.getValue() + " " + daySpinner.getValue());
    }//GEN-LAST:event_monthSpinnerStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton23jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton23jRadioButton3ActionPerformed

    private void jRadioButton22jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton22jRadioButton2ActionPerformed

    private void jRadioButton21jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton21jRadioButton1ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
detail tp = new detail(this, formUser); // kirim formUser

// Ambil data dari form
String selectedSize = jRadioButton21.isSelected() ? jRadioButton21.getText()
                    : jRadioButton22.isSelected() ? jRadioButton22.getText()
                    : jRadioButton23.isSelected() ? jRadioButton23.getText()
                    : "-";

String selectedToppings = "";
if (jCheckBox1.isSelected()) selectedToppings += jCheckBox1.getText() + "\n";
if (jCheckBox2.isSelected()) selectedToppings += jCheckBox2.getText() + "\n";
if (jCheckBox3.isSelected()) selectedToppings += jCheckBox3.getText() + "\n";
if (jCheckBox4.isSelected()) selectedToppings += jCheckBox4.getText() + "\n";
if (jCheckBox5.isSelected()) selectedToppings += jCheckBox5.getText() + "\n";
if (jCheckBox6.isSelected()) selectedToppings += jCheckBox6.getText() + "\n";

String crust = jRadioButton4.isSelected() ? jRadioButton4.getText()
             : jRadioButton5.isSelected() ? jRadioButton5.getText()
             : "-";

String sauce = jComboBox1.getSelectedItem().toString();
String pedas = String.valueOf(temperaturScrollBar.getValue());
String jenisPizza = monthSpinner.getValue().toString();
String jumlahPizza = daySpinner.getValue().toString();
String pembayaran = jList1.getSelectedValuesList().isEmpty() ? "-" : jList1.getSelectedValuesList().get(0).toString();
String total = totalCostTextField.getText();
//String alamat = jTextArea1.getText();

// Kirim ke form detail
tp.setDataDetail(
    selectedSize,
    selectedToppings.trim(),
    crust,
    sauce,
    pedas,
    jenisPizza,
    jumlahPizza,
    total,
    pembayaran
//    alamat
);

// Kirim data user
if (formUser != null) {
    String nama = formUser.getNameUser();
    String telepon = formUser.getPhoneUser();
    String alamat = formUser.getAlamat();
    tp.setDataUser(nama, telepon, alamat);
}
tp.setLocationRelativeTo(null);
tp.setVisible(true);


    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void Konversi() {
    // Mendapatkan nilai dari JScrollBar
    int level = temperaturScrollBar.getValue();
    FTextFiled.setText(" " + level);

    // Atur warna berdasarkan level 0–10
    if (level == 0) {
        panelNya.setBackground(new Color(204, 255, 204)); // Hijau sangat muda
    } else if (level == 1) {
        panelNya.setBackground(new Color(178, 255, 178)); // Hijau lebih muda
    } else if (level == 2) {
        panelNya.setBackground(new Color(153, 255, 153)); // Hijau muda
    } else if (level == 3) {
        panelNya.setBackground(new Color(127, 255, 127)); // Hijau sedang
    } else if (level == 4) {
        panelNya.setBackground(new Color(255, 204, 102)); // Oranye muda
    } else if (level == 5) {
        panelNya.setBackground(new Color(255, 178, 51)); // Oranye sedang
    } else if (level == 6) {
        panelNya.setBackground(new Color(255, 153, 51)); // Oranye tua
    } else if (level == 7) {
        panelNya.setBackground(new Color(255, 102, 0)); // Oranye pekat
    } else if (level == 8) {
        panelNya.setBackground(new Color(255, 51, 51)); // Merah muda
    } else if (level == 9) {
        panelNya.setBackground(new Color(255, 26, 26)); // Merah sedang
    } else if (level == 10) {
        panelNya.setBackground(new Color(204, 0, 0)); // Merah pekat
    } else {
        panelNya.setBackground(Color.GRAY); // Jika di luar jangkauan
    }
}
    
    private int tempF;
    
    private String S1 = "";

    private String S2 ="";
    
    public void setTabIndex(int index) {
        shoppingPane.setSelectedIndex(index); // 0 untuk tab pertama
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FLabel;
    private javax.swing.JTextField FTextFiled;
    private javax.swing.JTextArea TA1;
    private javax.swing.JTextArea TAA;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.ButtonGroup bg1;
    private javax.swing.ButtonGroup bg2;
    private javax.swing.ButtonGroup bg3;
    private javax.swing.JSpinner daySpinner;
    private javax.swing.JLabel gambar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFileChooser jFC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSpinner monthSpinner;
    private javax.swing.JPanel panelNya;
    private javax.swing.JTabbedPane shoppingPane;
    private javax.swing.JScrollBar temperaturScrollBar;
    private javax.swing.JTextField totalCostTextField;
    // End of variables declaration//GEN-END:variables
}
